name: 'Test Secrets'

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test AWS Credentials
        run: |
          echo "Testing AWS credentials..."
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-north-1
          aws sts get-caller-identity

      - name: Test Other Secrets
        run: |
          echo "Testing other secrets..."
          echo "Environment: ${{ secrets.ENVIRONMENT }}"
          echo "Key Name: ${{ secrets.KEY_NAME }}"
          echo "DB Username: ${{ secrets.DB_USERNAME }}"
          # Don't print the password for security
          echo "DB Password: [REDACTED]" 